### ISSUE TITLE
Consumable keys

### ISSUE THREAD

**Issue by ReshiStar** [Skyost/SerialKey#10] opened 2019-05-16 19:41 UTC
Could you please add the option for keys to be consumed when used?

**Comment by Skyost** [comment] 2019-05-16 21:35
If you set the option `reusable-keys` to `false` then it should work.

**Comment by ReshiStar** [comment] 2019-05-17 23:07
No, that doesnt work the same way, that only gives a key back when the locked item is destroyed. What I mean is that the key is used up when the locked item is accessed.

**Comment by Skyost** [comment] 2020-11-01 00:57
Closed as a duplicate of #8.

**Closed as completed by Skyost** 2020-11-01 00:57 UTC
Labels: enhancement
